-- 1. Create the admin role (if not exists)
INSERT INTO `roles` (`name`, `slug`, `created_at`, `updated_at`)
VALUES ('Admin', 'admin', NOW(), NOW())
ON DUPLICATE KEY UPDATE `updated_at` = NOW();

-- 2. Create the admin user
--    Password below is: password
--    (bcrypt hash generated by Laravel — change it after login!)
INSERT INTO `users`
  (`name`, `email`, `password`, `status`, `email_verified_at`, `created_at`, `updated_at`)
VALUES
  ('Super Admin',
   'admin@example.com',
   '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
   'active',
   NOW(), NOW(), NOW());

-- 3. Link the user to the admin role
INSERT INTO `role_user` (`user_id`, `role_id`, `created_at`, `updated_at`)
SELECT u.id, r.id, NOW(), NOW()
FROM `users` u, `roles` r
WHERE u.email = 'admin@example.com' AND r.slug = 'admin';